### ISSUE TITLE
pytorch-arm-python version 

### ISSUE THREAD

**Issue by SmallMunich** [nmilosev/pytorch-arm-builds#5]
Hi, @nmilosev. I want to know the pytorch-arm version  can compatible with the python 3.6 ?

**Comment by nmilosev** [comment]
There prebuilt ones are for 3.7. If you follow my linked build process, you could build for 3.6 but I think it is easier just to update your Python version (if possible).

**Comment by SmallMunich** [comment]
I have solved it. Thanks
